### ISSUE TITLE
Gestión de ficheros

### ISSUE THREAD

**Issue by davizinho5** [aigora/twE100_2122-inside-out#6]
Debéis definir el **formato de los ficheros** que vuestro programa genera y lee (por ejemplo, el [formato CSV](https://es.wikipedia.org/wiki/Valores_separados_por_comas) es muy común para almacenar datos), y debéis **implementar el código** necesario para generar y leer estos ficheros.
Esta implementación puede tener cambios en la versión definitiva.

**Comment by Glutenfreee** [comment]
void lectura_de_fichero(int n)
{
FILE *file;

    switch (n)
    {
    case 1:
        file = fopen("Laberinto 1.txt", "r");
        break;
    case 2:
        file = fopen("Laberinto 2.txt", "r");
        break;
    case 3:
        file = fopen("Laberinto 3.txt", "r");
        break;
    case 4:
        file = fopen("Laberinto 4.txt", "r");
        break;
    case 5:
        file = fopen("Laberinto 5.txt", "r");
        break;
    case 6:
        file = fopen("Laberinto 6.txt", "r");
        break;
    
    default:
        break;
    }
    if (file == NULL) {
        printf("\nError; Cannot open file");
        exit(1);
    }

    // leemos diensiónes laberinto
    char r;
    int i, j, k, kant, fil, col;

    for ( i = 0; i < 2; i++ ) {
        j = 1;
        k = 0;
        do {
            r = fgetc(file);
            if (r == '\n') break;

            kant = r - '0';
            /*printf("%d leido\n", kant);*/

            k = kant + (k * j);
            j = 10;
        } while (1);
        
        /*printf("%d leido total\n", k);*/

        if (i == 0) {
            fil = k;
        }
        else {
            col = k;
        }
    }

    // cargamos array
    int lab[100][100];
    i = 0;
    j = 0;

    r = fgetc(file);
    do
    {
        do
        {
            if (r != '\n') // para la primera vez que entra
            {
                lab[i][j] = r - '0';
                j++;
            }
            r = fgetc(file);
        } while (r != '\n' || j < col);

        i++;
        j = 0;
        r = fgetc(file);

       /* printf("\n");*/

    }  while (r != EOF || i < fil);

    /*printf("fin lectura fichero\n");*/
    fclose(file);
    movimiento(lab, fil, col);
    
}

void copia_en_fichero(char matriz[F][C])
{
FILE *pf;
int i, j, t=0;
char g;
// Abrimos fichero para escritura
printf("Elija donde quiere guardar el laberinto (1, 2, 3 o 4): ");

do
{
    scanf(" %c", &g);
switch (g)
{
case '1':
    pf = fopen("Laberinto 1.txt", "w");
    t=1;
    break;
case '2':
    pf = fopen("Laberinto 2.txt", "w");
    t=1;
    break;
case '3':
    pf = fopen("Laberinto 3.txt", "w");
    t=1;
    break;
case '4':
    pf = fopen("Laberinto 4.txt", "w");
    t=1;
    break;
case '5':
    pf = fopen("Laberinto 5.txt", "w");
    t=1;
    break;
case '6':
    pf = fopen("Laberinto 6.txt", "w");
    t=1;
    break;
default:

printf("Input no válido\n");
    break;
}
} while (t==0);

if (pf == NULL) 
{// Si el resultado es NULL mensaje de error
printf("Error al abrir el fichero.\n");
}
else 
{// Si ha funcionado, comienza escritura
fprintf(pf, "%d", F-1);
fprintf(pf, "\n");
fprintf(pf, "%d", C-2);
fprintf(pf, "\n");
for ( i = 1; i < F; i++)
{
    for ( j = 1; j < C-1; j++)
    {
        if (matriz[i][j]=='*')
        {
            fprintf(pf, "1");
        }
        else
        {
        fprintf(pf, "0");
        }
    }
    fprintf(pf, "\n");
}
fclose(pf);
}
}
