### ISSUE TITLE
Diagrama de flujo

### ISSUE THREAD

**Issue by davizinho5** [aigora/twE100_2122-inside-out#7]
Debéis crear un fichero en formato [PDF](https://help.github.com/en/articles/rendering-pdf-documents), [GIF, JPEG o PNG](https://help.github.com/en/articles/rendering-and-diffing-images) (**no se admiten documentos Word o similar**) representando el [diagrama de flujo](https://es.wikipedia.org/wiki/Diagrama_de_flujo) previsto para vuestro programa. 
En el punto de inicio tenéis un [tutorial](https://github.com/aigora/punto_inicio/wiki/6.1-C%C3%B3mo-realizar-un-diagrama-de-flujo) para crear diagramas de flujo.
Este diagrama os servirá de guía para la implementación del trabajo. No obstante, ésta será la primera versión, por lo que según vayáis avanzando en el desarrollo del programa podréis y deberéis modificarlo.

**Comment by almudenarp** [comment]
[DIAGRAMA FLUJO INFO (1).pdf](https://github.com/aigora/twE100_2122-inside-out/files/8676173/DIAGRAMA.FLUJO.INFO.1.pdf)

**Comment by davizinho5** [comment]
Buenas,

El diagrama debería ser un fichero que es parte de vuestro repositorio en alguno de los formatos que se indican en el mensaje de la issue.
Lo habéis pegado aquí pero no lo habéis puesto en el repositorio junto al código.
Hacedlo y volvéis a cerrar la issue.
